language: php

php:
    - 5.3
    - 5.4

env:
    - SYMFONY_VERSION=origin/2.1
    - SYMFONY_VERSION=origin/2.2
    - SYMFONY_VERSION=origin/2.3

script: phpunit --coverage-clover=coverage.clover

before_script:
    - composer self-update 
    - composer install --dev
