language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION=origin/2.7
    - SYMFONY_VERSION=origin/2.8

before_script:
    - composer self-update 
    - composer install

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/64a455d3354c06acfc92
    on_success: change
    on_failure: always
    on_start: false
